### ISSUE TITLE
Different from the description in source paper

### ISSUE THREAD

**Issue by xFLOWERRR** [baiksung/ALFA#1]
i am sorry to bother but i found that the function for calculating weight use a different way from the paper.

In the basic paper, we use "a 3-layer MLP with ReLU activation between the layers" as the weight creator. But in the code, i found the weight creator (function "get_per_step_loss_importance_vector") doesn't use MLP.

Is this because of my misunderstanding or some reasons else? Thanks for anyone who answering.

**Comment by baiksung** [comment]
Hi,

"get_per_step_loss_importance_vector" part is used for weighting losses when using multi-step optimization, which is inherited from [MAML++](https://github.com/AntreasAntoniou/HowToTrainYourMAMLPytorch).
But, if you see in config files, multi-step loss optimization is disabled.

You can find MLP in this [line](https://github.com/baiksung/ALFA/blob/4b0abd1c632b6c26a8d6e8ca861e773c08c22f08/few_shot_learning_system.py#L94).
In this code, we use a 2-layer MLP, instead of 3-layer MLP, as we noticed that it did not make significant differences. 

Hope this helps!

**Comment by xFLOWERRR** [comment]
thanks a lot for your answering. 


your code really helps me for my further work:)


On 2/15/2021 08:01，Sungyong Baik<notifications@github.com> wrote：

Hi,

"get_per_step_loss_importance_vector" part is used for weighting losses when using multi-step optimization, which is inherited from MAML++.
But, if you see in config files, multi-step loss optimization is disabled.

You can find MLP in this line.
In this code, we use a 2-layer MLP, instead of 3-layer MLP, as we noticed that it did not make significant differences.

Hope this helps!
