### ISSUE TITLE
Didn't understand the need for beta_dict_per_param

### ISSUE THREAD

**Issue by nightlessbaron** [baiksung/ALFA#2]
Hi @baiksung, 

I enjoyed reading your paper :)
As the title says, I didn't understand the need for initializing `names_beta_dict_per_param`.
https://github.com/baiksung/ALFA/blob/master/inner_loop_optimizers.py#L112

What does it do exactly?

**Comment by baiksung** [comment]
Hi @nightlessbaron,

Thanks for the interest in our work.
This a learnable beta (or 1-weight-decay-term) for each parameter.
While this is not used when ALFA is used together with MAML initialization, this is used when a random initialization is used instead of MAML.
In the case of a random initialization, fine-grained per-parameter prior knowledge is no longer present.
We thus introduced meta-learnable per-parameter weight-decay term to replace the role of MAML initialization in formulating the prior knowledge for each parameter of a base learner (as explained in the last paragraph of Section 3.3. in our paper).

Hope this helps! :)

**Comment by nightlessbaron** [comment]
Thanks, @baiksung.
