### ISSUE TITLE
Model Weight Dimension Misalignment in conv2d

### ISSUE THREAD

**Issue by Owen-Yang-18** [baiksung/ALFA#4]
Hi @baiksung 

I enjoyed reading your paper, it is very helpful and inspiring! I have encountered an issue when running maml+alfa.

When using the omniglot dataset (from MAML++), there seems to be a weight dimension misalignment when passing the F.conv2d model. The error log prints as follows: 
“File "C:\...\ALFA\meta_neural_network_architectures.py", line 391, in forward
    out = F.conv2d(input=x, weight=weight, bias=bias, stride=self.stride,
RuntimeError: Given groups=1, weight of size [48, 3, 3, 3], expected input[25, 1, 84, 84] to have 3 channels, but got 1 channels instead”
Is there a way to check explicitly or automatically align the weight dimensions?

Many thanks!

**Comment by baiksung** [comment]
Hi,

Thanks for the interests in our paper.
The error occurs because the image dimension is different for omniglot. For example, the `image_height` and `image_weight` should be `28` and the `image_channels` should be set to `1`. Hyperparameters, including image dimensions, should be changed in json files under `experiment_config` folder. You can refer to MAML++ public code and see how the hyperparameters (image dimensions are not the only difference) are usually set for omniglot.

Hope this helps!
